import type { ConsumptionRecord } from '@/types';

// 90-day window: 2025-11-21 to 2026-02-19
// Weekday usage is full rate; weekend usage is 40% of weekday
// Each component has a defined weekday daily rate

// Day-of-week for 2025-11-21 is Friday (5), we walk forward 90 days
// 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat

type RateMap = Record<string, number>;

const weekdayRates: RateMap = {
  'COMP-001': 85,   // Resistors: ~85/day weekday
  'COMP-002': 70,   // Caps: ~70/day weekday
  'COMP-003': 18,   // Elec caps: ~18/day
  'COMP-004': 12,   // Diodes: ~12/day
  'COMP-005': 15,   // Transistors: ~15/day
  'COMP-006': 3.5,  // STM32 MCU: 3.5/day → CRITICAL
  'COMP-007': 8,    // Voltage reg: ~8/day
  'COMP-008': 5,    // PCB: ~5/day → WARNING
  'COMP-009': 9,    // USB-C conn: ~9/day
  'COMP-010': 4.2,  // ABS housing: ~4.2/day → WARNING
  'COMP-011': 6,    // Ribbon cable: ~6/day
  'COMP-012': 35,   // Screws: ~35/day
  'COMP-013': 4.8,  // TFT display: 4.8/day → CRITICAL
  'COMP-014': 7,    // EEPROM: ~7/day
  'COMP-015': 5.5,  // RJ45: ~5.5/day
};

// Pre-computed consumption records as static array
// Generated by walking 2025-11-21 + 89 days = 2026-02-19 for each component

function buildRecords(): ConsumptionRecord[] {
  const records: ConsumptionRecord[] = [];

  const startDate = new Date('2025-11-21');
  const componentIds = Object.keys(weekdayRates);

  // Deterministic variation table: 90 offsets per component, fixed
  // Using a simple arithmetic pattern to avoid runtime randomness
  const variations90: number[] = [
    1.02, 0.97, 1.05, 0.98, 1.01, 0.96, 1.03, 0.99, 1.04, 0.97,
    1.00, 1.02, 0.95, 1.06, 0.98, 1.01, 0.97, 1.03, 0.99, 1.02,
    0.96, 1.04, 0.98, 1.01, 0.97, 1.03, 0.99, 1.02, 0.96, 1.04,
    0.98, 1.00, 0.97, 1.03, 0.99, 1.02, 0.96, 1.04, 0.98, 1.01,
    0.97, 1.05, 0.99, 1.02, 0.96, 1.04, 0.98, 1.01, 0.97, 1.03,
    0.99, 1.02, 0.95, 1.04, 0.98, 1.01, 0.97, 1.03, 0.99, 1.02,
    0.96, 1.04, 0.98, 1.01, 0.97, 1.03, 1.00, 1.02, 0.96, 1.04,
    0.98, 1.01, 0.97, 1.03, 0.99, 1.02, 0.96, 1.04, 0.97, 1.01,
    0.99, 1.02, 0.96, 1.03, 0.98, 1.01, 0.97, 1.04, 0.99, 1.02,
  ];

  for (const compId of componentIds) {
    const weekdayRate = weekdayRates[compId];
    for (let day = 0; day < 90; day++) {
      const d = new Date(startDate);
      d.setDate(startDate.getDate() + day);
      const dow = d.getDay(); // 0=Sun, 6=Sat
      const isWeekend = dow === 0 || dow === 6;
      const baseRate = isWeekend ? weekdayRate * 0.4 : weekdayRate;
      const variation = variations90[day];
      const unitsConsumed = Math.round(baseRate * variation * 10) / 10;

      const yyyy = d.getFullYear();
      const mm = String(d.getMonth() + 1).padStart(2, '0');
      const dd = String(d.getDate()).padStart(2, '0');

      records.push({
        componentId: compId,
        date: `${yyyy}-${mm}-${dd}`,
        unitsConsumed: unitsConsumed > 0 ? unitsConsumed : 0,
      });
    }
  }

  return records;
}

export const consumptionRecords: ConsumptionRecord[] = buildRecords();
